CREATE FUNCTION RANDBETWEEN(minval INTEGER, maxval INTEGER, random NUMERIC)
RETURNS INTEGER
AS $$
BEGIN
  RETURN (SELECT CAST((maxval - minval) * random + minval AS INTEGER));
END;
$$ LANGUAGE PLPGSQL;